// GENERATED by tools/fit_eval.py -- do not edit by hand.
//
// The shipped weights for layer 4's learned evaluation, in Eval.Scale fixed
// point.  Checked in rather than loaded from a file so that a campaign worker
// has no runtime dependency and two runs of the same binary rank identically;
// --eval-weights overrides them for a bench.
//
// fit on 19662 groups / 605 recordings (187 human + 465 solver), softmax-in-group, seed 12345
namespace LaserTank.Solver
{
    public static class Weights
    {
        public const string Source = "fit on 19662 groups / 605 recordings (187 human + 465 solver), softmax-in-group, seed 12345";

        public static readonly int[] Default =
        {
            // bias  work  work_far  flagdist  flag_unreach  manhattan
            0, 157, 13795, -11, 2979, 77,
            // route_obs  component  bricks  blocks  mirrors  antitanks
            180, 22, 215, 1197, 20, 897,
            // water  thin_ice  block_by_water  threats  far_man
            48, 40, -119, -487, -149,
        };
    }
}
