#!/usr/bin/env bash
# Item 5's cheap test: the fire tier against its own control, over the 138
# unsolved GAUNTLETs with a short record.
#
#   bash tools/gauntlet_tail.sh
#
# The population is bench/gauntlet-tail.txt and the report second_pass.sh wants
# is build/reports/gauntlet-tail.jsonl, both regenerated by the snippet in
# docs/solver/next-actions.md item 5.  Two arms, identical but for one flag, so
# the comparison is internal and needs nothing else to be comparable with: the
# arm ships or it does not on the union, per this file's fourth rule.
#
# Why these levels and not a campaign: a GAUNTLET's barrier set is empty by
# construction, so the read is inert on all of them and the fire tier is the
# only thing in the project with an opinion about the quantity that has to
# fall.  The 537 unsolved GAUNTLETs in the stride sample have a median record
# of 138; these 138 are the ones at <= 60, which is where a 40M-node budget has
# any chance at all.
set -u
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
exe="${LT_SOLVE:-$root/build/lasertank-solve.exe}"
first=$root/build/reports/gauntlet-tail.jsonl
L8="--push-reach --push-ferry-match --push-ferry-maze --push-dead 20
    --push-fire 8 --push-shot-run 16 --push-beam 128 --max-keys 5000"

run () {   # run <arm> <extra flags...>
  arm=$1; shift
  LT_SOLVE="$exe" NODES="${NODES:-40000000}" BUDGET_MS="${BUDGET_MS:-1800000}" \
  JOBS="${JOBS:-16}" bash "$root/tools/second_pass.sh" \
      "$first" "gt/$arm" "$root/build/reports/gt-$arm.jsonl" \
      --no-ida --no-beam --push --push-read \
      --max-keys 5000 --max-keys-record $L8 --push-eval work "$@"
  python "$root/tools/verify_solutions.py" "$root/build/gt/$arm"
}

run base
run fire --push-fire-tier

python "$root/tools/arms_union.py" base="$root/build/reports/gt-base.jsonl" \
                                   fire="$root/build/reports/gt-fire.jsonl"
